BUILDING_CODE_CATEGORIES = {
  'A': 'Single Family',
  'B': 'Two Family',
  'C': 'Walk-Up Apartments',
  'D': 'Elevator Apartments',
  'E': 'Warehouses',
  'F': 'Factories & Industrial',
  'G': 'Garages',
  'H': 'Hotels',
  'I': 'Hospitals & Health',
  'J': 'Theatres',
  'K': 'Stores',
  'L': 'Lofts',
  'M': 'Religious',
  'N': 'Asylums & Homes',
  'O': 'Office Buildings',
  'P': 'Indoor Assembly & Cultural',
  'Q': 'Outdoor Recreational',
  'R': 'Condos',
  'S': 'Mixed-Use',
  'T': 'Transportation',
  'U': 'Utility Bureau',
  'V': 'Vacant',
  'W': 'Educational',
  'Y': 'Government',
  'Z': 'Misc.'
}
