"""Add more flags to annotations

Revision ID: 0676e87608f8
Revises: d0fae47ada85
Create Date: 2024-04-18 11:39:16.781387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0676e87608f8'
down_revision: Union[str, None] = 'd0fae47ada85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unique_image_annotations', sa.Column('valid_roi', sa.Boolean(), nullable=True))
    op.add_column('unique_image_annotations', sa.Column('annotation_source', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unique_image_annotations', 'annotation_source')
    op.drop_column('unique_image_annotations', 'valid_roi')
    # ### end Alembic commands ###
