"""Add textract filename for annotations

Revision ID: 0a6d9eda457b
Revises: 31f6fb01c807
Create Date: 2024-05-02 12:20:36.314658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6d9eda457b'
down_revision: Union[str, None] = '31f6fb01c807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unique_image_annotations', sa.Column('textract_filename', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unique_image_annotations', 'textract_filename')
    # ### end Alembic commands ###
