"""Add gc charts table

Revision ID: 0dfe38526f6c
Revises: 2c46df3fe4c5
Create Date: 2024-03-07 10:10:14.714408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfe38526f6c'
down_revision: Union[str, None] = '2c46df3fe4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gc_charts',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('borough', sa.String(length=100), nullable=True),
    sa.Column('building_code', sa.String(length=100), nullable=True),
    sa.Column('dob_company_ids', sa.JSON(), nullable=False),
    sa.Column('deltas', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric', 'start_date', 'end_date', 'borough', 'building_code', name='uc_gc_permit_charts'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_gc_charts_created_at'), 'gc_charts', ['created_at'], unique=False)
    op.create_index(op.f('ix_gc_permit_rollups_average_estimated_job_costs'), 'gc_permit_rollups', ['average_estimated_job_costs'], unique=False)
    op.create_index(op.f('ix_gc_permit_rollups_median_estimated_job_costs'), 'gc_permit_rollups', ['median_estimated_job_costs'], unique=False)
    op.create_index(op.f('ix_gc_permit_rollups_num_permits'), 'gc_permit_rollups', ['num_permits'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gc_permit_rollups_num_permits'), table_name='gc_permit_rollups')
    op.drop_index(op.f('ix_gc_permit_rollups_median_estimated_job_costs'), table_name='gc_permit_rollups')
    op.drop_index(op.f('ix_gc_permit_rollups_average_estimated_job_costs'), table_name='gc_permit_rollups')
    op.drop_index(op.f('ix_gc_charts_created_at'), table_name='gc_charts')
    op.drop_table('gc_charts')
    # ### end Alembic commands ###
