"""Change cost columns to decimals

Revision ID: 136132577fdc
Revises: 30c2cd207949
Create Date: 2024-03-06 14:27:12.676691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136132577fdc'
down_revision: Union[str, None] = '30c2cd207949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dob_job_applications', 'initial_cost',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('dob_job_applications', 'estimated_job_costs',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dob_job_applications', 'estimated_job_costs',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('dob_job_applications', 'initial_cost',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
