"""Adding architectural page number probability

Revision ID: 1b2f35970d05
Revises: 0676e87608f8
Create Date: 2024-04-21 09:53:07.293249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2f35970d05'
down_revision: Union[str, None] = '0676e87608f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unique_images', sa.Column('architectural_page_number_probability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unique_images', 'architectural_page_number_probability')
    # ### end Alembic commands ###
