"""Add bid file annotations

Revision ID: 25278255d172
Revises: e6a629c2123f
Create Date: 2024-04-17 13:01:08.669972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25278255d172'
down_revision: Union[str, None] = 'e6a629c2123f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bc_bid_file_image_annotations',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bc_bid_file_image_id', sa.CHAR(32), nullable=False),
    sa.Column('page_number', sa.String(length=100), nullable=False),
    sa.Column('page_number_x', sa.Integer(), nullable=False),
    sa.Column('page_number_y', sa.Integer(), nullable=False),
    sa.Column('page_number_w', sa.Integer(), nullable=False),
    sa.Column('page_number_h', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bc_bid_file_image_id'], ['bc_bid_file_images.id'], name='fk_bcbfia_bc_bid_file_image_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bc_bid_file_image_id')
    )
    op.create_index(op.f('ix_bc_bid_file_image_annotations_created_at'), 'bc_bid_file_image_annotations', ['created_at'], unique=False)
    op.add_column('bc_bid_file_images', sa.Column('has_architectural_page_number', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bc_bid_file_images', 'has_architectural_page_number')
    op.drop_index(op.f('ix_bc_bid_file_image_annotations_created_at'), table_name='bc_bid_file_image_annotations')
    op.drop_table('bc_bid_file_image_annotations')
    # ### end Alembic commands ###
