"""Add dob job applications

Revision ID: 29898ada16d4
Revises: 98320999a450
Create Date: 2024-03-06 14:05:35.061011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29898ada16d4'
down_revision: Union[str, None] = '98320999a450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dob_job_applications',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('job_filing_number', sa.String(length=24), nullable=False),
    sa.Column('filing_status', sa.String(length=100), nullable=False),
    sa.Column('borough', sa.String(length=100), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('lot', sa.String(length=100), nullable=True),
    sa.Column('filing_date', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_filing_number')
    )
    op.drop_column('pluto_lots', 'is_commercial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pluto_lots', sa.Column('is_commercial', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('dob_job_applications')
    # ### end Alembic commands ###
