"""Update gc permit rollups

Revision ID: 2c46df3fe4c5
Revises: d289fa621fb7
Create Date: 2024-03-06 23:01:38.067550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c46df3fe4c5'
down_revision: Union[str, None] = 'd289fa621fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gc_permit_rollups', sa.Column('average_estimated_job_costs', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.create_unique_constraint('uc_gc_permit_rollups', 'gc_permit_rollups', ['dob_company_id', 'start_date', 'end_date', 'borough', 'building_code'])
    op.drop_column('gc_permit_rollups', 'avg_estimated_job_costs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gc_permit_rollups', sa.Column('avg_estimated_job_costs', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint('uc_gc_permit_rollups', 'gc_permit_rollups', type_='unique')
    op.drop_column('gc_permit_rollups', 'average_estimated_job_costs')
    # ### end Alembic commands ###
