"""Remove unique constraint on path on gc charts

Revision ID: 35fde61523ae
Revises: cfd6054b2d37
Create Date: 2024-03-07 22:09:51.862856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fde61523ae'
down_revision: Union[str, None] = 'cfd6054b2d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gc_charts_path_key', 'gc_charts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('gc_charts_path_key', 'gc_charts', ['path'])
    # ### end Alembic commands ###
