"""Add images extracted boolean

Revision ID: 3da186e738ab
Revises: 4e133a2f1037
Create Date: 2024-04-17 12:43:50.202030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da186e738ab'
down_revision: Union[str, None] = '4e133a2f1037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bc_bid_file_images',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bc_bid_file_id', sa.CHAR(32), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('local_filename', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['bc_bid_file_id'], ['bc_bids.id'], name='fk_bc_bid_file_images_bc_bids_id_bc_bid_file_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bc_bid_file_id', 'page_number', name='uc_bc_bid_file_images_bc_bid_file_id_page_number')
    )
    op.create_index(op.f('ix_bc_bid_file_images_created_at'), 'bc_bid_file_images', ['created_at'], unique=False)
    op.add_column('bc_bid_files', sa.Column('images_extracted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bc_bid_files', 'images_extracted')
    op.drop_index(op.f('ix_bc_bid_file_images_created_at'), table_name='bc_bid_file_images')
    op.drop_table('bc_bid_file_images')
    # ### end Alembic commands ###
