"""rename columns in annotation

Revision ID: 449f38f294a5
Revises: 25278255d172
Create Date: 2024-04-17 15:09:42.434216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449f38f294a5'
down_revision: Union[str, None] = '25278255d172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bc_bid_file_image_annotations', sa.Column('page_number_x1', sa.Integer(), nullable=False))
    op.add_column('bc_bid_file_image_annotations', sa.Column('page_number_y1', sa.Integer(), nullable=False))
    op.add_column('bc_bid_file_image_annotations', sa.Column('page_number_x2', sa.Integer(), nullable=False))
    op.add_column('bc_bid_file_image_annotations', sa.Column('page_number_y2', sa.Integer(), nullable=False))
    op.drop_column('bc_bid_file_image_annotations', 'page_number_h')
    op.drop_column('bc_bid_file_image_annotations', 'page_number_x')
    op.drop_column('bc_bid_file_image_annotations', 'page_number_y')
    op.drop_column('bc_bid_file_image_annotations', 'page_number_w')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bc_bid_file_image_annotations', sa.Column('page_number_w', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bc_bid_file_image_annotations', sa.Column('page_number_y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bc_bid_file_image_annotations', sa.Column('page_number_x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bc_bid_file_image_annotations', sa.Column('page_number_h', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bc_bid_file_image_annotations', 'page_number_y2')
    op.drop_column('bc_bid_file_image_annotations', 'page_number_x2')
    op.drop_column('bc_bid_file_image_annotations', 'page_number_y1')
    op.drop_column('bc_bid_file_image_annotations', 'page_number_x1')
    # ### end Alembic commands ###
