"""Add filenames to bid file

Revision ID: 4e133a2f1037
Revises: db1a6d32b4e9
Create Date: 2024-04-17 11:23:34.430789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e133a2f1037'
down_revision: Union[str, None] = 'db1a6d32b4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bc_bid_files', sa.Column('local_filename', sa.String(length=100), nullable=True))
    op.add_column('bc_bid_files', sa.Column('mime_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bc_bid_files', 'mime_type')
    op.drop_column('bc_bid_files', 'local_filename')
    # ### end Alembic commands ###
