"""Add valid flag to annotation candidates

Revision ID: 6eb6b4bf1c47
Revises: 449f38f294a5
Create Date: 2024-04-17 16:09:42.440927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb6b4bf1c47'
down_revision: Union[str, None] = '449f38f294a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bc_bid_file_image_annotations', sa.Column('valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bc_bid_file_image_annotations', 'valid')
    # ### end Alembic commands ###
