"""Add borough, lot data to dob permits, add pluto table

Revision ID: 98320999a450
Revises: 45df64d91dad
Create Date: 2024-03-05 15:16:15.774378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98320999a450'
down_revision: Union[str, None] = '45df64d91dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pluto_lots',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('borough', sa.String(length=100), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('lot', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('building_code', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_commercial', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('borough', 'block', 'lot', name='uc_pluto_lots_borough_block_lot')
    )
    op.add_column('dob_approved_permits', sa.Column('borough', sa.String(length=100), nullable=True))
    op.add_column('dob_approved_permits', sa.Column('block', sa.String(length=100), nullable=True))
    op.add_column('dob_approved_permits', sa.Column('lot', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dob_approved_permits', 'lot')
    op.drop_column('dob_approved_permits', 'block')
    op.drop_column('dob_approved_permits', 'borough')
    op.drop_table('pluto_lots')
    # ### end Alembic commands ###
