"""Add is complete to charts

Revision ID: 998d063ae73b
Revises: 0dfe38526f6c
Create Date: 2024-03-07 10:43:50.276406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '998d063ae73b'
down_revision: Union[str, None] = '0dfe38526f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gc_charts', sa.Column('is_complete', sa.Boolean(), nullable=False))
    op.alter_column('gc_charts', 'dob_company_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('gc_charts', 'deltas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gc_charts', 'deltas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('gc_charts', 'dob_company_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('gc_charts', 'is_complete')
    # ### end Alembic commands ###
