"""remove associated chart ids in gc chart

Revision ID: 9cd8560fd162
Revises: a104fb9f36c8
Create Date: 2024-03-12 11:40:12.528338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd8560fd162'
down_revision: Union[str, None] = 'a104fb9f36c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gc_charts', 'previous_gc_chart_id')
    op.drop_column('gc_charts', 'parent_gc_chart_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gc_charts', sa.Column('parent_gc_chart_id', sa.CHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('gc_charts', sa.Column('previous_gc_chart_id', sa.CHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
