"""Adjust dob permit table

Revision ID: c76dd7e76281
Revises: aea37bc6ed57
Create Date: 2024-03-01 13:38:44.485711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76dd7e76281'
down_revision: Union[str, None] = 'aea37bc6ed57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_dob_approved_permit_pk', 'dob_approved_permits', ['job_filing_number', 'filing_reason', 'work_type', 'applicant_business_id'])
    op.drop_column('dob_approved_permits', 'address')
    op.drop_column('dob_approved_permits', 'work_on_floor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dob_approved_permits', sa.Column('work_on_floor', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('dob_approved_permits', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('uc_dob_approved_permit_pk', 'dob_approved_permits', type_='unique')
    # ### end Alembic commands ###
