"""migrate towards unique images

Revision ID: c91b4c390a39
Revises: 6eb6b4bf1c47
Create Date: 2024-04-17 16:30:09.163727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c91b4c390a39'
down_revision: Union[str, None] = '6eb6b4bf1c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unique_images',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('md5_hash', sa.String(length=100), nullable=False),
    sa.Column('local_filename', sa.String(length=100), nullable=True),
    sa.Column('has_architectural_page_number', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unique_images_created_at'), 'unique_images', ['created_at'], unique=False)
    op.create_table('unique_image_annotations',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('unique_image_id', sa.CHAR(32), nullable=False),
    sa.Column('page_number', sa.String(length=100), nullable=False),
    sa.Column('page_number_x1', sa.Integer(), nullable=False),
    sa.Column('page_number_y1', sa.Integer(), nullable=False),
    sa.Column('page_number_x2', sa.Integer(), nullable=False),
    sa.Column('page_number_y2', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['unique_image_id'], ['unique_images.id'], name='fk_unique_image_annotations_unique_images_id_unique_image_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unique_image_annotations_created_at'), 'unique_image_annotations', ['created_at'], unique=False)
    op.drop_index('ix_bc_bid_file_image_annotations_created_at', table_name='bc_bid_file_image_annotations')
    op.drop_table('bc_bid_file_image_annotations')
    op.add_column('bc_bid_file_images', sa.Column('unique_image_id', sa.CHAR(32), nullable=False))
    op.create_foreign_key('fk_bc_bid_file_images_unique_images_id_unique_image_id', 'bc_bid_file_images', 'unique_images', ['unique_image_id'], ['id'])
    op.drop_column('bc_bid_file_images', 'has_architectural_page_number')
    op.drop_column('bc_bid_file_images', 'local_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bc_bid_file_images', sa.Column('local_filename', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('bc_bid_file_images', sa.Column('has_architectural_page_number', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_bc_bid_file_images_unique_images_id_unique_image_id', 'bc_bid_file_images', type_='foreignkey')
    op.drop_column('bc_bid_file_images', 'unique_image_id')
    op.create_table('bc_bid_file_image_annotations',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bc_bid_file_image_id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('page_number_x1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_number_y1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_number_x2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_number_y2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bc_bid_file_image_id'], ['bc_bid_file_images.id'], name='fk_bcbfia_bc_bid_file_image_id'),
    sa.PrimaryKeyConstraint('id', name='bc_bid_file_image_annotations_pkey'),
    sa.UniqueConstraint('bc_bid_file_image_id', name='bc_bid_file_image_annotations_bc_bid_file_image_id_key')
    )
    op.create_index('ix_bc_bid_file_image_annotations_created_at', 'bc_bid_file_image_annotations', ['created_at'], unique=False)
    op.drop_index(op.f('ix_unique_image_annotations_created_at'), table_name='unique_image_annotations')
    op.drop_table('unique_image_annotations')
    op.drop_index(op.f('ix_unique_images_created_at'), table_name='unique_images')
    op.drop_table('unique_images')
    # ### end Alembic commands ###
