"""remove top gcs infra

Revision ID: d0fae47ada85
Revises: c91b4c390a39
Create Date: 2024-04-17 16:49:59.463677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0fae47ada85'
down_revision: Union[str, None] = 'c91b4c390a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gc_chart_rankings_created_at', table_name='gc_chart_rankings')
    op.drop_table('gc_chart_rankings')
    op.drop_index('ix_dob_job_applications_created_at', table_name='dob_job_applications')
    op.drop_table('dob_job_applications')
    op.drop_index('ix_dob_approved_permits_created_at', table_name='dob_approved_permits')
    op.drop_table('dob_approved_permits')
    op.drop_index('ix_gc_charts_created_at', table_name='gc_charts')
    op.drop_table('gc_charts')
    op.drop_index('ix_pluto_lots_created_at', table_name='pluto_lots')
    op.drop_table('pluto_lots')
    op.drop_index('ix_gc_permit_rollups_average_estimated_job_costs', table_name='gc_permit_rollups')
    op.drop_index('ix_gc_permit_rollups_created_at', table_name='gc_permit_rollups')
    op.drop_index('ix_gc_permit_rollups_median_estimated_job_costs', table_name='gc_permit_rollups')
    op.drop_index('ix_gc_permit_rollups_num_permits', table_name='gc_permit_rollups')
    op.drop_table('gc_permit_rollups')
    op.drop_index('ix_dob_companies_created_at', table_name='dob_companies')
    op.drop_table('dob_companies')
    op.create_unique_constraint(None, 'unique_images', ['md5_hash'])
    op.create_unique_constraint(None, 'unique_images', ['local_filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unique_images', type_='unique')
    op.drop_constraint(None, 'unique_images', type_='unique')
    op.create_table('gc_permit_rollups',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dob_company_id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('borough', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('building_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('num_permits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('median_estimated_job_costs', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('average_estimated_job_costs', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dob_company_id'], ['dob_companies.id'], name='fk_gc_permit_rollups_dob_companies_id_dob_company_id'),
    sa.PrimaryKeyConstraint('id', name='gc_permit_rollups_pkey'),
    sa.UniqueConstraint('dob_company_id', 'start_date', 'end_date', 'borough', 'building_code', name='uc_gc_permit_rollups')
    )
    op.create_index('ix_gc_permit_rollups_num_permits', 'gc_permit_rollups', ['num_permits'], unique=False)
    op.create_index('ix_gc_permit_rollups_median_estimated_job_costs', 'gc_permit_rollups', ['median_estimated_job_costs'], unique=False)
    op.create_index('ix_gc_permit_rollups_created_at', 'gc_permit_rollups', ['created_at'], unique=False)
    op.create_index('ix_gc_permit_rollups_average_estimated_job_costs', 'gc_permit_rollups', ['average_estimated_job_costs'], unique=False)
    op.create_table('pluto_lots',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('borough', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('block', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lot', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('building_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('normalized_borough', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pluto_lots_pkey'),
    sa.UniqueConstraint('borough', 'block', 'lot', name='uc_pluto_lots_borough_block_lot')
    )
    op.create_index('ix_pluto_lots_created_at', 'pluto_lots', ['created_at'], unique=False)
    op.create_table('dob_companies',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dob_companies_pkey'),
    sa.UniqueConstraint('name', name='dob_companies_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_dob_companies_created_at', 'dob_companies', ['created_at'], unique=False)
    op.create_table('gc_charts',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('borough', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('building_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('permits_rolled_up_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rankings_synced_dat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gc_charts_pkey'),
    sa.UniqueConstraint('slug', name='gc_charts_slug_key'),
    sa.UniqueConstraint('start_date', 'end_date', 'borough', 'building_code', name='uc_gc_permit_charts'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_gc_charts_created_at', 'gc_charts', ['created_at'], unique=False)
    op.create_table('dob_approved_permits',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('job_filing_number', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('filing_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('work_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('applicant_business_id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('approved_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('issued_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('borough', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('block', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lot', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estimated_job_costs', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('normalized_borough', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['applicant_business_id'], ['dob_companies.id'], name='fk_dob_approved_permits_dob_companies_id_applicant_business_id'),
    sa.PrimaryKeyConstraint('id', name='dob_approved_permits_pkey'),
    sa.UniqueConstraint('job_filing_number', 'filing_reason', 'work_type', 'applicant_business_id', 'issued_date', name='uc_dob_approved_permit_pk')
    )
    op.create_index('ix_dob_approved_permits_created_at', 'dob_approved_permits', ['created_at'], unique=False)
    op.create_table('dob_job_applications',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('job_filing_number', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('filing_status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('borough', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('block', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lot', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('filing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('initial_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dob_job_applications_pkey'),
    sa.UniqueConstraint('job_filing_number', name='dob_job_applications_job_filing_number_key')
    )
    op.create_index('ix_dob_job_applications_created_at', 'dob_job_applications', ['created_at'], unique=False)
    op.create_table('gc_chart_rankings',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('gc_chart_id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('metric', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dob_company_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('deltas', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gc_chart_id'], ['gc_charts.id'], name='fk_gc_chart_rankings_gc_charts_id_gc_chart_id'),
    sa.PrimaryKeyConstraint('id', name='gc_chart_rankings_pkey'),
    sa.UniqueConstraint('gc_chart_id', 'metric', name='uc_gc_chart_rankings_gc_chart_id_metric')
    )
    op.create_index('ix_gc_chart_rankings_created_at', 'gc_chart_rankings', ['created_at'], unique=False)
    # ### end Alembic commands ###
