"""Add normalized boroughs, add gc permit rollups

Revision ID: d289fa621fb7
Revises: ebcb34ab753c
Create Date: 2024-03-06 22:46:37.354317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd289fa621fb7'
down_revision: Union[str, None] = 'ebcb34ab753c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dob_approved_permits', sa.Column('normalized_borough', sa.String(length=100), nullable=True))
    op.add_column('gc_permit_rollups', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('gc_permit_rollups', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('gc_permit_rollups', sa.Column('avg_estimated_job_costs', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('gc_permit_rollups', sa.Column('median_estimated_job_costs', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.alter_column('gc_permit_rollups', 'borough',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('gc_permit_rollups', 'building_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('gc_permit_rollups', 'month')
    op.drop_column('gc_permit_rollups', 'estimated_job_costs')
    op.add_column('pluto_lots', sa.Column('normalized_borough', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pluto_lots', 'normalized_borough')
    op.add_column('gc_permit_rollups', sa.Column('estimated_job_costs', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('gc_permit_rollups', sa.Column('month', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('gc_permit_rollups', 'building_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('gc_permit_rollups', 'borough',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('gc_permit_rollups', 'median_estimated_job_costs')
    op.drop_column('gc_permit_rollups', 'avg_estimated_job_costs')
    op.drop_column('gc_permit_rollups', 'end_date')
    op.drop_column('gc_permit_rollups', 'start_date')
    op.drop_column('dob_approved_permits', 'normalized_borough')
    # ### end Alembic commands ###
