"""Add bid files

Revision ID: db1a6d32b4e9
Revises: fcad0bd04102
Create Date: 2024-04-16 14:05:53.571219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1a6d32b4e9'
down_revision: Union[str, None] = 'fcad0bd04102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bc_bid_files', sa.Column('parent_folder_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bc_bid_files', 'parent_folder_id')
    # ### end Alembic commands ###
