"""Add confidence to annotation

Revision ID: e1b3ff39d144
Revises: e2ccbb9a53f4
Create Date: 2024-05-02 15:39:13.189570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b3ff39d144'
down_revision: Union[str, None] = 'e2ccbb9a53f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unique_image_annotations', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unique_image_annotations', 'confidence')
    # ### end Alembic commands ###
