"""Fix fk mistake on bc bid file image

Revision ID: e6a629c2123f
Revises: 1efd186397d9
Create Date: 2024-04-17 12:49:25.944797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a629c2123f'
down_revision: Union[str, None] = '1efd186397d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bc_bid_file_images_bc_bids_id_bc_bid_file_id', 'bc_bid_file_images', type_='foreignkey')
    op.create_foreign_key('fk_bc_bid_file_images_bc_bid_files_id_bc_bid_file_id', 'bc_bid_file_images', 'bc_bid_files', ['bc_bid_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bc_bid_file_images_bc_bid_files_id_bc_bid_file_id', 'bc_bid_file_images', type_='foreignkey')
    op.create_foreign_key('fk_bc_bid_file_images_bc_bids_id_bc_bid_file_id', 'bc_bid_file_images', 'bc_bids', ['bc_bid_file_id'], ['id'])
    # ### end Alembic commands ###
