"""Add index on created at columns

Revision ID: ebcb34ab753c
Revises: 4ace62bfa087
Create Date: 2024-03-06 18:43:19.139783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcb34ab753c'
down_revision: Union[str, None] = '4ace62bfa087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gc_permit_rollups',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dob_company_id', sa.CHAR(32), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('borough', sa.String(length=100), nullable=False),
    sa.Column('building_code', sa.String(length=100), nullable=False),
    sa.Column('num_permits', sa.Integer(), nullable=False),
    sa.Column('estimated_job_costs', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['dob_company_id'], ['dob_companies.id'], name='fk_gc_permit_rollups_dob_companies_id_dob_company_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_permit_rollups_created_at'), 'gc_permit_rollups', ['created_at'], unique=False)
    op.create_index(op.f('ix_bc_bids_created_at'), 'bc_bids', ['created_at'], unique=False)
    op.create_index(op.f('ix_bc_companies_created_at'), 'bc_companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_dob_approved_permits_created_at'), 'dob_approved_permits', ['created_at'], unique=False)
    op.create_index(op.f('ix_dob_companies_created_at'), 'dob_companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_dob_job_applications_created_at'), 'dob_job_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_pluto_lots_created_at'), 'pluto_lots', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pluto_lots_created_at'), table_name='pluto_lots')
    op.drop_index(op.f('ix_dob_job_applications_created_at'), table_name='dob_job_applications')
    op.drop_index(op.f('ix_dob_companies_created_at'), table_name='dob_companies')
    op.drop_index(op.f('ix_dob_approved_permits_created_at'), table_name='dob_approved_permits')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_index(op.f('ix_bc_companies_created_at'), table_name='bc_companies')
    op.drop_index(op.f('ix_bc_bids_created_at'), table_name='bc_bids')
    op.drop_index(op.f('ix_gc_permit_rollups_created_at'), table_name='gc_permit_rollups')
    op.drop_table('gc_permit_rollups')
    # ### end Alembic commands ###
