"""Add bid files

Revision ID: fcad0bd04102
Revises: 9cd8560fd162
Create Date: 2024-04-16 13:22:03.471834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcad0bd04102'
down_revision: Union[str, None] = '9cd8560fd162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bc_bid_files',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bc_bid_id', sa.CHAR(32), nullable=False),
    sa.Column('bc_id', sa.String(length=24), nullable=False),
    sa.Column('file_system_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bc_bid_id'], ['bc_bids.id'], name='fk_bc_bid_files_bc_bids_id_bc_bid_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bc_bid_id', 'bc_id', name='uc_bc_bid_files_bc_bid_id_bc_id')
    )
    op.create_index(op.f('ix_bc_bid_files_created_at'), 'bc_bid_files', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bc_bid_files_created_at'), table_name='bc_bid_files')
    op.drop_table('bc_bid_files')
    # ### end Alembic commands ###
